import Link from "next/link";

export default function Privacy() {
  return (
      <article className="max-w-4xl mx-auto px-4 py-10 flex flex-col gap-12">
      <section className="flex flex-col gap-4">
        <h1 className="text-4xl font-bold">Privacy Policy</h1>
        <div className="text-sm text-muted-foreground">
          Last updated: 06th July 2025
        </div>
      </section>
      <section className="flex flex-col gap-4">
        <h2 className="text-2xl font-semibold">1. Introduction</h2>
        <p>
          Welcome to Ikiform ("us", "we", or "our") which operates Ikiform
          (website/mobile application) (hereinafter referred to as "Service").
          Our Privacy Policy governs your visit to Ikiform (website/mobile
          application), and explains how we collect, safeguard and disclose
          information that results from your use of our Service. We use your
          data to provide and improve Service. By using Service, you agree to
          the collection and use of information in accordance with this policy.
          Unless otherwise defined in this Privacy Policy, the terms used in
          this Privacy Policy have the same meanings as in our Terms and
          Conditions. Our Terms and Conditions ("Terms") govern all use of our
          Service and together with the Privacy Policy constitute your agreement
          with us ("Agreement").
        </p>
      </section>
      <section className="flex flex-col gap-4">
        <h2 className="text-2xl font-semibold">2. Definitions</h2>
        <ul className="list-disc pl-6 flex flex-col gap-1">
          <li>
            <b>Cookies</b>: Small files stored on your device (computer or
            mobile device);
          </li>
          <li>
            <b>Data Controller</b>: A natural or legal person who determines the
            purposes for which and the manner in which any personal data are
            processed. For the purpose of this Privacy Policy, we are a Data
            Controller of your data;
          </li>
          <li>
            <b>Data Processors</b> or <b>Service Provider</b>: Any natural or
            legal person who processes the data on behalf of the Data
            Controller. We may use the services of various Service Providers in
            order to process your data more effectively;
          </li>
          <li>
            <b>Data Subject</b>: Any living individual who is the subject of
            Personal Data;
          </li>
          <li>
            <b>Personal Data</b>: Data about a living individual who can be
            identified from those data (or from those and other information
            either in our possession or likely to come into our possession);
          </li>
          <li>
            <b>Service</b>: The Ikiform (website/mobile application);
          </li>
          <li>
            <b>Usage Data</b>: Data collected automatically either generated by
            the use of Service or from Service infrastructure itself (for
            example, the duration of a page visit); and
          </li>
          <li>
            <b>User(s)</b>: The person(s) using our Service and who corresponds
            to the Data Subject, which is the subject of Personal Data.
          </li>
        </ul>
      </section>
      <section className="flex flex-col gap-4">
        <h2 className="text-2xl font-semibold">
          3. Information Collection and Use
        </h2>
        <p>
          We collect several different types of information for various purposes
          to provide and improve our Service to you.
        </p>
      </section>
      <section className="flex flex-col gap-4">
        <h2 className="text-2xl font-semibold">4. Types of Data Collected</h2>
        <div className="flex flex-col gap-4">
          <div>
            <h3 className="text-lg font-semibold">a. Personal Data</h3>
            <p>
              While using our Service, we may ask you to provide us with certain
              personally identifiable information that can be used to contact or
              identify you ("Personal Data"). Personally identifiable
              information may include, but is not limited to:
            </p>
            <ul className="list-disc pl-6 flex flex-col gap-1">
              <li>Email address;</li>
              <li>First name and last name;</li>
              <li>Phone number;</li>
              <li>Address, State, Province, ZIP/Postal code, City; and/or</li>
              <li>Cookies and Usage Data.</li>
            </ul>
            <p>
              We may use your Personal Data to contact you with newsletters,
              marketing or promotional materials and other information that may
              be of interest to you. You may opt out of receiving any, or all,
              of these communications from us by following the unsubscribe link
              or by emailing to{" "}
              <Link
                href="mailto:hi@ikiform.com"
                className="text-blue-500 underline"
              >
                hi@ikiform.com
              </Link>
              .
            </p>
          </div>
          <div>
            <h3 className="text-lg font-semibold">b. Usage Data</h3>
            <p>
              We may also collect information that your browser sends whenever
              you visit our Service or when you access Service by or through a
              mobile device. This Usage Data may include information such as
              your computer's Internet Protocol address (e.g. IP address),
              browser type, browser version, the pages of our Service that you
              visit, the time and date of your visit, the time spent on those
              pages, unique device identifiers and other diagnostic data. When
              you access Service with a mobile device, this Usage Data may
              include information such as the type of mobile device you use,
              your mobile device unique ID, the IP address of your mobile
              device, your mobile operating system, the type of mobile Internet
              browser you use, unique device identifiers and other diagnostic
              data.
            </p>
          </div>
        </div>
      </section>
      <section className="flex flex-col gap-4">
        <h2 className="text-2xl font-semibold">5. Use of Data</h2>
        <p>Ikiform uses the collected data for various purposes such as:</p>
        <ul className="list-disc pl-6 flex flex-col gap-1">
          <li>To provide and maintain our Service;</li>
          <li>To notify you about changes to our Service;</li>
          <li>
            To allow you to participate in interactive features of our Service
            when you choose to do so;
          </li>
          <li>To provide customer support;</li>
          <li>
            To gather analysis or valuable information so that we can improve
            our Service;
          </li>
          <li>To monitor the usage of our Service;</li>
          <li>To detect, prevent and address technical issues;</li>
          <li>To fulfill any other purpose for which you provide it;</li>
          <li>
            To carry out our obligations and enforce our rights arising from any
            contracts entered into between you and us, including for billing and
            collection;
          </li>
          <li>
            To provide you with notices about your account and/or subscription,
            including expiration and renewal notices, email-instructions, etc.;
          </li>
          <li>
            To provide you with news, special offers and general information
            about other goods, services and events which we offer that are
            similar to those that you have already purchased or enquired about
            unless you have opted not to receive such information;
          </li>
          <li>
            In any other way we may describe when you provide the information;
            and
          </li>
          <li>For any other purpose with your consent.</li>
        </ul>
      </section>
      <section className="flex flex-col gap-4">
        <h2 className="text-2xl font-semibold">6. Retention of Data</h2>
        <p>
          We will retain your Personal Data only for as long as is necessary for
          the purposes set out in this Privacy Policy. We will retain and use
          your Personal Data to the extent necessary to comply with our legal
          obligations, resolve disputes, and enforce our legal agreements and
          policies.
        </p>
        <p>
          We will also retain Usage Data for internal analysis purposes. Usage
          Data is generally retained for a shorter period, except when this data
          is used to strengthen the security or to improve the functionality of
          our Service, or we are legally obligated to retain this data for
          longer time periods.
        </p>
      </section>
      <section className="flex flex-col gap-4">
        <h2 className="text-2xl font-semibold">7. Transfer of Data</h2>
        <p>
          Your information, including Personal Data, may be transferred to and
          maintained on computers located outside of your state, province,
          country or other governmental jurisdiction where the data protection
          laws may differ from those of your jurisdiction.
        </p>
        <p>
          If you are located outside India and choose to provide information to
          us, please note that we transfer the data, including Personal Data, to
          India and process it there.
        </p>
        <p>
          Your consent to this Privacy Policy followed by your submission of
          such information represents your agreement to that transfer.
        </p>
        <p>
          Ikiform will take all the steps reasonably necessary to ensure that
          your data is treated securely and in accordance with this Privacy
          Policy and no transfer of your Personal Data will take place to an
          organisation or a country unless there are adequate controls in place
          including the security of your data and other personal information.
        </p>
        <p>
          For more details about our subprocessors, please see our{" "}
          <Link href="/legal/gdpr" className="text-blue-500 underline">
            GDPR Compliance Page
          </Link>
          .
        </p>
      </section>
      <section className="flex flex-col gap-4">
        <h2 className="text-2xl font-semibold">8. Payments</h2>
        <p>
          We may provide paid products and/or services within Service. In that
          case, we use third-party services for payment processing (e.g. payment
          processors).
        </p>
        <p>
          We will not store or collect your payment card details. That
          information is provided directly to our third-party payment processors
          whose use of your personal information is governed by their Privacy
          Policy.
        </p>
      </section>
      <section className="flex flex-col gap-4">
        <h2 className="text-2xl font-semibold">
          9. Changes to This Privacy Policy
        </h2>
        <p>
          We may update our Privacy Policy from time to time. We will notify you
          of any changes by posting the new Privacy Policy on this page. We will
          let you know via email and/or a prominent notice on our Service, prior
          to the change becoming effective and update "effective date" at the
          top of this Privacy Policy. You are advised to review this Privacy
          Policy periodically for any changes. Changes to this Privacy Policy
          are effective when they are posted on this page.
        </p>
      </section>
      <section className="flex flex-col gap-4">
        <h2 className="text-2xl font-semibold">10. Contact Us</h2>
        <p>
          If you have any questions about this Privacy Policy, please contact
          us:{" "}
          <Link
            href="mailto:hi@ikiform.com"
            className="text-blue-500 underline"
          >
            hi@ikiform.com
          </Link>
        </p>
      </section>
      </article>
  );
}
